listener 1883 0.0.0.0
allow_anonymous false
password_file /tmp/ods-mqtt/passwords
acl_file /mosquitto/config/acl
persistence true
persistence_location /mosquitto/data/
autosave_interval 60
log_dest stdout
connection_messages false
max_connections 100
message_size_limit 1048576
max_queued_messages 1000
sys_interval 5
