bind 0.0.0.0
protected-mode yes
port 6379
daemonize no
loglevel notice
logfile ""
dir /data
databases 1
aclfile /tmp/ods-users.acl
maxclients 100
maxmemory 128mb
maxmemory-policy noeviction
appendonly yes
appendfsync everysec
save ""
tcp-keepalive 300
