listeners.tcp.default = 5672
management.tcp.port = 15672
vm_memory_high_watermark.absolute = 1GB
disk_free_limit.absolute = 1GB
channel_max = 128
max_message_size = 16777216
auth_mechanisms.1 = PLAIN
auth_mechanisms.2 = AMQPLAIN
anonymous_login_user = none
log.console = true
log.file = false
