version: 0.1
log:
  level: info
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: false
http:
  addr: :5000
  relativeurls: true
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: ods-registry
    path: /tmp/ods-registry/htpasswd
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
